[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "City Tech CUTgroup Resources"
authors = [{name = "Meera Raja", email = "meera.raja@gmail.com"}]
dynamic = ["version", "description"]
